# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{api_docs}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jack Neto", "The Working Group Inc."]
  s.date = %q{2012-05-02}
  s.description = %q{}
  s.email = %q{jack@twg.ca}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "api_docs.gemspec",
    "app/assets/javascripts/api_docs.js.coffee",
    "app/assets/javascripts/prettify.js",
    "app/assets/stylesheets/prettify.css",
    "app/views/api_docs/_api_docs.html.haml",
    "app/views/api_docs/_curl.html.haml",
    "app/views/api_docs/_form.html.haml",
    "app/views/api_docs/_panel.html.haml",
    "app/views/api_docs/_params.html.haml",
    "app/views/api_docs/_response.html.haml",
    "lib/api_docs.rb",
    "lib/api_docs/configuration.rb",
    "lib/api_docs/engine.rb",
    "lib/api_docs/railtie.rb"
  ]
  s.homepage = %q{http://github.com/twg/api_docs}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A tool to help you generate documentation for you API}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.1.0"])
      s.add_runtime_dependency(%q<bootstrap_builder>, [">= 0.2.6"])
    else
      s.add_dependency(%q<rails>, [">= 3.1.0"])
      s.add_dependency(%q<bootstrap_builder>, [">= 0.2.6"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.1.0"])
    s.add_dependency(%q<bootstrap_builder>, [">= 0.2.6"])
  end
end

